name: Build and host Pyodide

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Pyodide
        uses: pyodide/pyodide-build@v1
        with:
          pyodide-version: "0.27.7"
          packages: "numpy scipy matplotlib plotly mpld3 periodictable blinker dill orsopy"

      - name: Upload Pyodide build to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
